version: '2.1'

services:
  testsql:
   
   image: saishree31/login:1.0
   restart: always
   mem_limit: 2g
   environment: 
    - JAVA_OPTS= "-XX:+UnlockExperimentalVMOptions 
                  -XX:+UseCGroupMemoryLimitForHeap"
   network_mode: "host"
   hostname: localhost
   ports:
    - 8070:8070
   container_name: login
   depends_on:
    
    mysql:
     condition: service_healthy
   healthcheck:
    test: "exit 0"



 
  
